### ISSUE TITLE
Username and password of webdav server should be added in a secure way

### ISSUE THREAD

**Issue by ale8193** [ale8193/doc-node#17]
https://github.com/ale8193/doc-node/blob/cea9b89b315698e5a14b2f3145811ba009d98288/src/plugins/destination/webdav.js#L14-L30

It's necessary to find a clean solution to obtain username and password securely

**Comment by ecavina** [comment]
A simple approach (without external secret storage) is to use the variables passed at the time of launch (to local process, not for whole system). This can be done in two ways:

1) command line parameters and these parameters are then found in process.argv
node myapp.js username password
process.argv[2] will be "username" and process.argv[3] will be "password"

2) environment variables and these parameters are then found in process.env (two ways: inline with command launch and in the local user)
 
Drawbacks:
- history
- in a script, command line parameters may be hardcoded
- it is possibile to show variables from inside the host ("ps" / "/proc/<pid>/environ" from root user or user who defined it)

Solutions:
- create a specific user with least privileges, switch to this user, launch application with this user after settings environment variables (only this user can show them)

**Comment by sabbio93** [comment]
Since we need to manage access to multiple platforms as WebDAV swift etc etc
we can consider relying on an internal/external account/secret storage like Vault or docker secret or .....
As first approach that comes to mind is to apply the adapter interface wrapper as we already made in others part of the project. The architecture (where to place, how to manage, who uses the SS) is not easy as pie.

**Comment by ecavina** [comment]
I added a module to get username and password in different ways more secure than hardcoded. A possibile mode that is implemented but not yet tested is with Docker secrets (need swarm and compose): [how to](https://daten-und-bass.io/blog/using-docker-secrets-with-nodejs/)
