### ISSUE TITLE
Add a route to get the volume list of a specific container

### ISSUE THREAD

**Issue by ale8193** [ale8193/doc-node#21]
Add a route to get the volume list of a specific container. This route should get the ID of the container as parameter and should return an array of volumes. The route will be a GET route with path `api/v{version}/containers/{id}/volumes`

**Comment by ale8193** [comment]
The necessity of this route comes from the central server application (deloreanUp) that need to show the list of volumes of a single container.

We should consider if it is better to create this route that return only the volumes of the container or if it is better to create a more general route that return a single container object with all its parameters (included the list of volumes)

**Comment by ale8193** [comment]
After some analysis of the problem I think it is better to create a general route that return the container object of the container passed by its ID

**Comment by sabbio93** [comment]
Create both 
api/v{version}/containers/{id}/: returns a json object representing the container with a filed volumes.
api/v{version}/containers/{id}/volumes: returns only the object volumes
