### ISSUE TITLE
Error on Backup object creation

### ISSUE THREAD

**Issue by ale8193** [ale8193/doc-node#8]
The following creation of a new object raises this error: 
```
TypeError: BackupObject is not a constructor
```

https://github.com/ale8193/doc-node/blob/00452d5540cc6dcd6743eec1ff7b75dbe32e42d7/src/plugins/docker/containers.js#L46-L49

**Comment by sabbio93** [comment]
can't mix export module.exports import and require
export => import
module.exports => require
https://github.com/webpack/webpack/issues/4039

**Comment by sabbio93** [comment]
This problem is to indagate as we can have further problems while using both 
export => import
module.exports => require
